# Generated by Django 4.0.9 on 2023-02-24 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('averageratings', '0002_alter_averagerating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagerating',
            name='user',
        ),
        migrations.AddField(
            model_name='averagerating',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='merchant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
