# Generated by Django 4.0.7 on 2023-01-06 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0003_alter_cart_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_merchant', to=settings.AUTH_USER_MODEL),
        ),
    ]
