# Generated by Django 4.0.7 on 2023-01-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
