# Generated by Django 4.0.9 on 2023-02-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=8, null=True),
        ),
    ]
