# Generated by Django 4.0.9 on 2023-02-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchantinfo', '0010_alter_merchantinfo_display_picture'),
        ('carts', '0007_cart_delivery_cost_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='merchant_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_info', to='merchantinfo.merchantinfo'),
        ),
    ]
