apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-deployment
  labels:
    app: django-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-deployment
  template:
    metadata:
      labels:
        app: django-k8s-deployment
    spec:
      containers:
      - name: django-k8s
        image: registry.digitalocean.com/zaanzain-k8s/django-k8s-web:v1
        envFrom:
          - secretRef:
              name: django-k8s-web-prod-env
        env:
          - name: PORT
            value: "8001"
        ports:
        - containerPort: 8001
      imagePullSecrets:
        - name: zaanzain-k8s

---
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: django-k8s-deployment