# Generated by Django 4.0.7 on 2022-11-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=120),
        ),
    ]
