# Generated by Django 4.0.7 on 2022-11-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='serving',
            new_name='servings',
        ),
    ]
