# Generated by Django 4.0.7 on 2022-12-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_order',
            field=models.IntegerField(default=1),
        ),
    ]
