# Generated by Django 4.0.9 on 2023-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantinfo', '0005_alter_merchantinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantinfo',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='merchantinfo',
            name='delivery_free_cutoff',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=12),
        ),
    ]
