# Generated by Django 4.0.9 on 2023-02-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantinfo', '0006_merchantinfo_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantinfo',
            name='delivery_free_cutoff',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=12, null=True),
        ),
    ]
