# Generated by Django 4.0.9 on 2023-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantinfo', '0007_alter_merchantinfo_delivery_free_cutoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantinfo',
            name='delivery_free_cutoff',
            field=models.DecimalField(decimal_places=1, default=1000000, max_digits=12),
        ),
    ]
