# Generated by Django 4.0.9 on 2023-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantinfo', '0008_alter_merchantinfo_delivery_free_cutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantinfo',
            name='min_order',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
