# Generated by Django 4.0.9 on 2023-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantinfo', '0009_merchantinfo_min_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantinfo',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='display_picture'),
        ),
    ]
