# Generated by Django 4.0.9 on 2023-03-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchantinfo', '0010_alter_merchantinfo_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantinfo',
            name='delivery_radius',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
