name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test_django_job:
    uses: denialAll/DJANGO-K8S/.github/workflows/test-django.yaml@master
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      CLUSTER_NAME: django-k8s
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: Login to DO Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
    - name: Build container image  
      run: |
        cd ./web
        docker build -f Dockerfile \
          -t registry.digitalocean.com/zaanzain-k8s/django-k8s-web:latest \
          -t registry.digitalocean.com/zaanzain-k8s/django-k8s-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
          .
    - name: Push Image
      run: |
        docker push registry.digitalocean.com/zaanzain-k8s/django-k8s-web --all-tags
    - name: K8s cluster kubeconfig file with/ short-lived creds
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
    - name: Update deployment secrets
      run: |
        cat << EOF >> web/.env.prod
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY_ID=${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        EOF
        kubectl create secret generic django-k8s-web-prod-env --from-env-file=web/.env.prod
    - name: Update Deployment image
      run: |
        kubectl set image deployment/django-k8s-web-deployment django-k8s-web=registry.digitalocean.com/
        zaanzain-k8s/django-k8s-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
    - name: Wait for rollout to complete
      run: |
        kubectl rollout status deployment/django-k8s-web-deployment
    - name: Post-build Django Commands - Migrate / Collectstatic
      run: |
        export SINGLE_POD_NAME=$(kubectl get pod -l app=django-k8s-web-deployment -o jsonpath="{.items[0].metadata.name}")
        kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
        kubectl exec -it $SINGLE_POD_NAME -- bash /app/collectstatic.sh
    